CREATE TABLE
    IS601_Users(
        id int AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(60) UNIQUE,
        password VARCHAR(60) NOT NULL,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )